#!/usr/bin/env bash
# setup.sh — Project bootstrap script
#
# Guides a new developer through:
#   1. Installing the FlutterFire CLI
#   2. Configuring Firebase for all flavors
#   3. Creating a .env file with PostHog credentials
#   4. Printing a next-steps checklist
#
# Usage: bash setup.sh
# Or (after chmod +x setup.sh): ./setup.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

confirm() {
  read -r -p "$1 [y/N] " response
  [[ "$response" =~ ^[Yy]$ ]]
}

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

echo ""
echo -e "${CYAN}=================================================${RESET}"
echo -e "${CYAN}   Flutter BLoC Base — Project Setup Script      ${RESET}"
echo -e "${CYAN}=================================================${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Collect Firebase project ID
# ---------------------------------------------------------------------------

info "Step 1: Firebase project configuration"
echo ""
read -r -p "  Enter your Firebase project ID (or press Enter to skip): " FIREBASE_PROJECT_ID

if [[ -z "$FIREBASE_PROJECT_ID" ]]; then
  warn "No Firebase project ID provided — skipping FlutterFire configuration."
  warn "Run 'flutterfire configure --project=<YOUR_PROJECT_ID>' later."
  SKIP_FIREBASE=true
else
  SKIP_FIREBASE=false
fi

# ---------------------------------------------------------------------------
# Step 2: Collect PostHog API key
# ---------------------------------------------------------------------------

echo ""
info "Step 2: PostHog analytics configuration"
echo ""
read -r -p "  Enter your PostHog API key (or press Enter to skip): " POSTHOG_API_KEY
read -r -p "  Enter your PostHog host URL (default: https://app.posthog.com): " POSTHOG_HOST
POSTHOG_HOST="${POSTHOG_HOST:-https://app.posthog.com}"

# ---------------------------------------------------------------------------
# Step 3: Check / install Flutter and Dart
# ---------------------------------------------------------------------------

echo ""
info "Step 3: Checking Flutter installation"
if ! command -v flutter &> /dev/null; then
  error "Flutter is not installed. Install from https://flutter.dev/docs/get-started/install"
fi
FLUTTER_VERSION=$(flutter --version 2>&1 | head -1)
success "Flutter found: $FLUTTER_VERSION"

# ---------------------------------------------------------------------------
# Step 4: Check / install FlutterFire CLI
# ---------------------------------------------------------------------------

echo ""
info "Step 4: Checking FlutterFire CLI"
if ! command -v flutterfire &> /dev/null; then
  warn "FlutterFire CLI not found."
  if confirm "  Install FlutterFire CLI now? (dart pub global activate flutterfire_cli)"; then
    dart pub global activate flutterfire_cli
    success "FlutterFire CLI installed"
  else
    warn "Skipping FlutterFire CLI install — you can install it later with:"
    warn "  dart pub global activate flutterfire_cli"
    SKIP_FIREBASE=true
  fi
else
  FLUTTERFIRE_VERSION=$(flutterfire --version 2>&1 | head -1)
  success "FlutterFire CLI found: $FLUTTERFIRE_VERSION"
fi

# ---------------------------------------------------------------------------
# Step 5: Run flutterfire configure
# ---------------------------------------------------------------------------

if [[ "$SKIP_FIREBASE" == false ]]; then
  echo ""
  info "Step 5: Running flutterfire configure for project '$FIREBASE_PROJECT_ID'"
  warn "This will overwrite lib/firebase_options.dart if it exists."
  if confirm "  Continue with flutterfire configure?"; then
    flutterfire configure --project="$FIREBASE_PROJECT_ID"
    success "Firebase options generated at lib/firebase_options.dart"
  else
    warn "Skipped — run manually: flutterfire configure --project=$FIREBASE_PROJECT_ID"
  fi
else
  info "Step 5: Skipped (no Firebase project ID)"
fi

# ---------------------------------------------------------------------------
# Step 6: Create .env file
# ---------------------------------------------------------------------------

echo ""
info "Step 6: Creating .env file"
ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env file already exists — skipping to avoid overwriting secrets."
else
  cat > "$ENV_FILE" <<EOF
# Environment variables — DO NOT commit this file to version control
# Generated by setup.sh on $(date +%Y-%m-%d)

POSTHOG_API_KEY=${POSTHOG_API_KEY}
POSTHOG_HOST=${POSTHOG_HOST}

# Add other secrets below:
# SOME_API_KEY=
EOF
  success ".env file created"
  warn "Make sure .env is in your .gitignore!"
fi

# ---------------------------------------------------------------------------
# Step 7: Run flutter pub get
# ---------------------------------------------------------------------------

echo ""
info "Step 7: Running flutter pub get"
flutter pub get
success "Dependencies fetched"

# ---------------------------------------------------------------------------
# Step 8: Next-steps checklist
# ---------------------------------------------------------------------------

echo ""
echo -e "${CYAN}=================================================${RESET}"
echo -e "${CYAN}   Setup Complete — Next Steps Checklist         ${RESET}"
echo -e "${CYAN}=================================================${RESET}"
echo ""
echo -e "  ${GREEN}[√]${RESET} Flutter dependencies installed"
[[ "$SKIP_FIREBASE" == false ]] && \
  echo -e "  ${GREEN}[√]${RESET} Firebase options generated (lib/firebase_options.dart)" || \
  echo -e "  ${YELLOW}[ ]${RESET} Run: flutterfire configure --project=<YOUR_PROJECT_ID>"
[[ -f ".env" ]] && \
  echo -e "  ${GREEN}[√]${RESET} .env file created" || \
  echo -e "  ${YELLOW}[ ]${RESET} Create .env file with PostHog API key"
echo ""
echo -e "  ${YELLOW}Manual steps required:${RESET}"
echo -e "  [ ] iOS: Add APNs certificate/key in Firebase Console → Cloud Messaging"
echo -e "  [ ] iOS: Add GoogleService-Info.plist to ios/Runner/ via Xcode (not file copy)"
echo -e "  [ ] Android: Confirm google-services.json is in android/app/"
echo -e "  [ ] Android: Verify google-services Gradle plugin is applied"
echo -e "  [ ] App Check: Register your app in Firebase Console → App Check"
echo -e "  [ ] Update FirebaseInitializer to import firebase_options.dart once generated:"
echo -e "        import 'package:flutter_bloc_base_source_code/firebase_options.dart';"
echo -e "        await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);"
echo -e "  [ ] Run build_runner: flutter pub run build_runner build --delete-conflicting-outputs"
echo -e "  [ ] Test on a real device (FCM / App Check do not work on simulators)"
echo ""
echo -e "${CYAN}Docs: https://firebase.flutter.dev/docs/overview${RESET}"
echo ""
