import 'dart:io';

import 'package:yaml_edit/yaml_edit.dart';

import 'setup_options.dart';

class ProjectFiles {
  const ProjectFiles(this.root);

  final Directory root;

  String readPubspecName() {
    final content = _file('pubspec.yaml').readAsStringSync();
    final match = RegExp(
      r'^name:\s*([^\s#]+)',
      multiLine: true,
    ).firstMatch(content);
    if (match == null) {
      throw StateError('pubspec.yaml is missing a top-level name field.');
    }
    return match.group(1)!;
  }

  String writePackageRenameConfig(ProjectSetupOptions options) {
    final directory = _directory('.dart_tool/project_setup')
      ..createSync(recursive: true);
    final configFile = File('${directory.path}/package_rename_config.yaml');
    configFile.writeAsStringSync(_packageRenameConfig(options));
    return configFile.path;
  }

  void updatePubspec(ProjectSetupOptions options) {
    final pubspec = _file('pubspec.yaml');
    final editor = YamlEditor(pubspec.readAsStringSync());
    editor.update(['name'], options.dartPackageName);
    if (options.description != null) {
      editor.update(['description'], options.description);
    }
    pubspec.writeAsStringSync(editor.toString());
  }

  List<String> rewriteDartPackageImports(String oldPackage, String newPackage) {
    if (oldPackage == newPackage) return const [];
    final paths = _trackedDartFiles();
    final changed = <String>[];
    for (final path in paths) {
      final file = _file(path);
      final original = file.readAsStringSync();
      final updated = original.replaceAll(
        'package:$oldPackage/',
        'package:$newPackage/',
      );
      if (updated != original) {
        file.writeAsStringSync(updated);
        changed.add(path);
      }
    }
    return changed;
  }

  bool writeEnvIfMissing(ProjectSetupOptions options) {
    final env = _file('.env');
    if (env.existsSync()) return false;
    env.writeAsStringSync('''
# Environment variables - DO NOT commit this file.
# Generated by dart run project_setup.

POSTHOG_API_KEY=${options.posthogApiKey ?? ''}
POSTHOG_HOST=${options.posthogHost}

# Add other secrets below:
# SOME_API_KEY=
''');
    return true;
  }

  bool ensureGitignoreEnv() {
    final gitignore = _file('.gitignore');
    if (!gitignore.existsSync()) {
      gitignore.writeAsStringSync('.env\n');
      return true;
    }
    final content = gitignore.readAsStringSync();
    if (RegExp(r'(^|\n)\.env(\n|$)').hasMatch(content)) {
      return false;
    }
    final separator = content.endsWith('\n') ? '' : '\n';
    gitignore.writeAsStringSync('$content$separator.env\n');
    return true;
  }

  bool updateFirebaseInitializerIfGenerated(String dartPackageName) {
    if (!_file('lib/firebase_options.dart').existsSync()) return false;
    final initializer = _file('lib/core/firebase/firebase_initializer.dart');
    var content = initializer.readAsStringSync();
    final importLine =
        "import 'package:$dartPackageName/firebase_options.dart';";
    content = content.replaceAll(
      RegExp(r"import 'package:[^']+/firebase_options\.dart';\n"),
      '',
    );
    if (!content.contains(importLine)) {
      content = content.replaceFirst(
        "import 'package:firebase_core/firebase_core.dart';\n",
        "import 'package:firebase_core/firebase_core.dart';\n$importLine\n",
      );
    }
    content = content.replaceFirst(
      'await Firebase.initializeApp();',
      'await Firebase.initializeApp(\n'
          '        options: DefaultFirebaseOptions.currentPlatform,\n'
          '      );',
    );
    initializer.writeAsStringSync(content);
    return true;
  }

  File _file(String relativePath) => File('${root.path}/$relativePath');

  Directory _directory(String relativePath) =>
      Directory('${root.path}/$relativePath');

  List<String> _trackedDartFiles() {
    final result = Process.runSync('git', [
      'ls-files',
      '*.dart',
    ], workingDirectory: root.path);
    if (result.exitCode == 0) {
      return (result.stdout as String)
          .split('\n')
          .where((path) => path.trim().isNotEmpty)
          .toList();
    }
    return root
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path.substring(root.path.length + 1))
        .where(
          (path) => path.endsWith('.dart') && !path.startsWith('.dart_tool/'),
        )
        .toList();
  }

  String _packageRenameConfig(ProjectSetupOptions options) {
    final appName = _quote(options.appName);
    final appId = _quote(options.appId);
    final exeName = _quote(options.dartPackageName);
    final organization = _quote(options.organization);
    final description = _quote(
      options.description ?? '${options.appName} Flutter app.',
    );
    return '''
package_rename_config:
  android:
    app_name: $appName
    package_name: $appId
    lang: kotlin
  ios:
    app_name: $appName
    bundle_name: $appName
    package_name: $appId
  linux:
    app_name: $appName
    package_name: $appId
    exe_name: $exeName
  macos:
    app_name: $appName
    package_name: $appId
    copyright_notice: ${_quote('Copyright (C) 2026 ${options.organization}. All rights reserved.')}
  web:
    app_name: $appName
    short_app_name: $appName
    description: $description
  windows:
    app_name: $appName
    organization: $organization
    copyright_notice: ${_quote('Copyright (C) 2026 ${options.organization}. All rights reserved.')}
    exe_name: $exeName
''';
  }

  String _quote(String value) =>
      '"${value.replaceAll(r'\', r'\\').replaceAll('"', r'\"')}"';
}
