import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:flutter/foundation.dart';

// Top-level background message handler required by FCM.
// Must be a top-level function (not a method).
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Background messages are handled here.
  // Firebase must already be initialized when this runs.
  debugPrint('[FCM] Background message: ${message.messageId}');
}

/// Initializes Firebase services with graceful fallback.
///
/// If Firebase is not configured (no google-services.json / GoogleService-Info.plist),
/// initialization fails silently and the app continues without Firebase.
/// All services check [isInitialized] before performing any operations.
///
/// To configure Firebase, run `flutterfire configure` after installing
/// the FlutterFire CLI: `dart pub global activate flutterfire_cli`
abstract class FirebaseInitializer {
  static bool _initialized = false;

  /// Whether Firebase was successfully initialized.
  static bool get isInitialized => _initialized;

  /// Initialize Firebase and all sub-services.
  ///
  /// Wraps the entire initialization in a try-catch so the app launches
  /// even without Firebase configuration files.
  static Future<void> initialize() async {
    try {
      // NOTE: DefaultFirebaseOptions is generated by `flutterfire configure`.
      // Until configured, Firebase.initializeApp() will throw — caught below.
      await Firebase.initializeApp();
      _initialized = true;
      debugPrint('[Firebase] Core initialized successfully');

      // Initialize sub-services independently — one failure doesn't block others.
      await _initCrashlytics();
      await _initRemoteConfig();
      await _initAppCheck();
      await _initMessaging();
    } on Exception catch (e, stack) {
      _initialized = false;
      debugPrint(
        '[Firebase] Init failed: $e — app continues without Firebase\n$stack',
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Sub-initializers
  // ---------------------------------------------------------------------------

  static Future<void> _initCrashlytics() async {
    try {
      // Disable automatic data collection in debug mode.
      await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(
        !kDebugMode,
      );
      debugPrint('[Firebase] Crashlytics initialized');
    } on Exception catch (e) {
      debugPrint('[Firebase] Crashlytics init failed: $e');
    }
  }

  static Future<void> _initRemoteConfig() async {
    try {
      final remoteConfig = FirebaseRemoteConfig.instance;
      await remoteConfig.setConfigSettings(
        RemoteConfigSettings(
          // Shorter interval in debug for faster iteration.
          fetchTimeout: const Duration(minutes: 1),
          minimumFetchInterval: kDebugMode
              ? const Duration(minutes: 1)
              : const Duration(hours: 12),
        ),
      );
      debugPrint('[Firebase] RemoteConfig initialized');
    } on Exception catch (e) {
      debugPrint('[Firebase] RemoteConfig init failed: $e');
    }
  }

  static Future<void> _initAppCheck() async {
    try {
      await FirebaseAppCheck.instance.activate(
        // Use DebugProvider in debug builds; platform providers in release.
        providerAndroid: kDebugMode
            ? const AndroidDebugProvider()
            : const AndroidPlayIntegrityProvider(),
        providerApple: kDebugMode
            ? const AppleDebugProvider()
            : const AppleDeviceCheckProvider(),
      );
      debugPrint('[Firebase] AppCheck initialized');
    } on Exception catch (e) {
      debugPrint('[Firebase] AppCheck init failed: $e');
    }
  }

  static Future<void> _initMessaging() async {
    try {
      FirebaseMessaging.onBackgroundMessage(
        firebaseMessagingBackgroundHandler,
      );
      debugPrint('[Firebase] Messaging initialized');
    } on Exception catch (e) {
      debugPrint('[Firebase] Messaging init failed: $e');
    }
  }
}
